#!/usr/bin/env bash
# Author: Pawel Jonik https://github.com/paweljonik
#
# Script to switch Wacom Cintiq input between different outputs/monitors.
#

__usage="
${0}

Toggles Wacom Cintiq input between output displays. 
Stores state in ~/.cintiq-display-toggle.state
"
getprop="ddcutil --mfg=WAC getvcp"
setprop="ddcutil --mfg=WAC setvcp"

if [[ $1 == "--help" ]]
then
	echo "${__usage}"
	exit
fi


state_file="${HOME}/.cintiq-display-toggle.state"
monitors=$(xrandr --listmonitors | grep Monitors | cut -d ' ' -f 2 )
cintiqs="$( xsetwacom list devices | cut -f 2 | cut -f 2 -d ':' )"
current_monitor=0
next_monitor=$((current_monitor + 1))

if [ -e "${state_file}" ]; then
	if [[ ${monitors} != $( tail -n1 "${state_file}") ]]; then
		rm ${state_file}
		echo "${next_monitor}" > "${state_file}"
		echo "${monitors}" >> "${state_file}"
	fi
	current_monitor=$( head -n1 "${state_file}" )
	if [[ ${current_monitor} -eq $((monitors - 1)) ]]; then
		next_monitor=0
	else
		next_monitor=$((current_monitor + 1))
	fi
else
	echo "${current_monitor}" > "${state_file}"
	echo "${monitors}" >> "${state_file}"
fi

for cintiq in ${cintiqs[@]}; do
	xsetwacom set $(echo ${cintiq} | tr -d '[:space:]' ) MapToOutput HEAD-${next_monitor}
	echo "${next_monitor}" > "${state_file}"
done
echo "${monitors}" >> "${state_file}"