#!/usr/bin/env bash
# Author: Pawel Jonik https://github.com/paweljonik
#
# Modify Wacom Cintiq screen settings.
#
__usage="
Usage: $( basename $0 ) [brightness: 0-100] [contrast: 0-100] [color-profile]
"
__help="Color profile values:
  1 for sRGB
  2 for Display Native
  4 for 5000 K
  5 for 6500 K
  6 for 7500 K
  8 for 9300 K
  11 for User 1

--help			- print this message
--usage			- print usage
--factory-defaults	- reset to factory defaults
--bc-defaults		- reset brightness and contrast to defaults
--color-defaults	- reset color profile to defaults
"

getprop="ddcutil --mfg=WAC getvcp"
setprop="ddcutil --mfg=WAC setvcp"

case "$1" in
"--help")
	echo "${__usage}"
	echo "${__help}"
	exit
;;
"--usage")
	echo "${__usage}"
	exit
;;
"--factory-defaults")
	${setprop} 04 1
	exit
;;
"--bc-defaults")
	${setprop} 05 1
	exit
;;
"--color-defaults")
	${setprop} 08 1
	exit
;;
*)
	echo "${__usage}"
	;;
esac

case "$#" in
1)
	${setprop} 10 $1
;;
2)
	${setprop} 10 $1
	${setprop} 12 $2
;;
3)
	${setprop} 10 $1
	${setprop} 12 $2
	${setprop} 14 $3
;;
esac

# Get values:
brightness="$( ${getprop} 10 | cut -c 67-69 )"
contrast="$( ${getprop} 12 | cut -c 67-69 )"
color="$( ${getprop} 14 | cut -c 58-72 )"

# printf "\nBrightness:\t ${brightness}\n"
# printf "Contrast:\t ${contrast}\n"
printf "\nBrightness: \t|"
for v in $( seq 0 $( bc <<< ${brightness}/2 ) ); do printf "■"; done	# or █
for v in $( seq $(bc <<< ${brightness}/2 ) 50 ); do printf "·"; done
printf "|${brightness}"

printf "\nContrast: \t|"
for v in $( seq 0 $( bc <<< ${contrast}/2 ) ); do printf "■"; done
for v in $( seq $(bc <<< ${contrast}/2 ) 50 ); do printf "-"; done
printf "|${contrast}\n"

printf "Color:\t\t ${color}\n\n"

# TODO:
# arguments validation
# Other useful values:
# Set Factory defaults
#$setprop 04 1
# Set Brightness/Contrast factory defaults:
#$setprop 05 1
# Set Color factory defaults:
#$setprop 08 1
