#!/usr/bin/env bash
# Author: Pawel Jonik https://github.com/paweljonik
#
# Script to switch Wacom inputs between different outputs/monitors.
#

__usage="
$( basename $0 ) [monitor]

Toggles Wacom inputs between output displays or 
sets them to a given [monitor] (LVDS-1 / HDMI-2 / etc.
or HEAD-1 / HEAD-2 for NVidia drivers & XRandr <1.2.
Map it to some hotkey for best experience :).
"

if [[ $1 == "--help" ]]
then
	echo "${__usage}"
	exit
fi


wacoms="$( xsetwacom list devices | rev | cut -f 2 | cut -f 1 -d ' ' | rev )"

if [[ -e ${1} ]]; then
	for wacom in ${wacoms[@]}; do
		xsetwacom set $( echo ${wacom} | tr -d '[:space:]' ) MapToOutput ${1}
		exit
	done
else
	for wacom in ${wacoms[@]}; do
		xsetwacom set $( echo ${wacom} | tr -d '[:space:]' ) MapToOutput next
		exit
	done
fi
